name: Update JSON files every minute

on:
  schedule:
    - cron: "*/1 * * * *"  # हर 1 मिनट में चलेगा
  workflow_dispatch:  # इसे मैन्युअली भी चला सकते हैं

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: रिपॉजिटरी को क्लोन करें
        uses: actions/checkout@v3

      - name: Python सेटअप करें
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: JSON डेटा डाउनलोड करें
        run: python fetch_json.py

      - name: गिट में बदलाव कमिट करें
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add profiles.json reels.json
          git commit -m "Auto-update JSON files" || echo "No changes to commit"
          git push
