- name: JSON डेटा डाउनलोड करें (Custom Headers)
        run: |
          curl -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64)" -b "cookie_name=cookie_value" -o profiles.json "http://msmpr.free.nf/profiles.json"
          curl -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64)" -b "cookie_name=cookie_value" -o reels.json "http://msmpr.free.nf/reels.json"
          cat profiles.json
          cat reels.json
