name: Auto Update JSON Files

on:
  schedule:
    - cron: '0 * * * *' # Har ghante
  workflow_dispatch:

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch reels.json
        run: |
          curl -v -o reels.json http://msmpr.free.nf/reels.json || echo "Failed to fetch reels.json"
          if [ ! -s reels.json ]; then echo "reels.json is empty or not downloaded"; exit 1; fi

      - name: Fetch profiles.json
        run: |
          curl -v -o profiles.json http://msmpr.free.nf/profiles.json || echo "Failed to fetch profiles.json"
          if [ ! -s profiles.json ]; then echo "profiles.json is empty or not downloaded"; exit 1; fi

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add reels.json profiles.json
          git commit -m "Auto-update JSON files from msmpr.free.nf" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
