name: Update JSON files every minute

on:
  schedule:
    - cron: "*/1 * * * *"  # हर 1 मिनट में रन होगा
  workflow_dispatch:  # मैन्युअली भी रन कर सकते हैं

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: रिपॉज़िटरी को क्लोन करें
        uses: actions/checkout@v3

      - name: JSON डेटा डाउनलोड करें
        run: |
          curl -o profiles.json http://msmpr.free.nf/profiles.json
          curl -o reels.json http://msmpr.free.nf/reels.json

      - name: गिट कमिट और पुश करें
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add profiles.json reels.json
          git commit -m "Auto-update JSON files" || exit 0
          git push
