- name: JSON डेटा डाउनलोड करें (Bypass JavaScript Challenge)
        run: |
          curl -o profiles.json "https://api.allorigins.win/raw?url=http://msmpr.free.nf/profiles.json"
          curl -o reels.json "https://api.allorigins.win/raw?url=http://msmpr.free.nf/reels.json"
          cat profiles.json
          cat reels.json
