name: Auto Update JSON Files

on:
  schedule:
    - cron: '0 * * * *' # Har ghante
  workflow_dispatch:

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch reels.json
        run: |
          curl -v -o ./reels.json http://msmpr.free.nf/reels.json || echo "Failed to fetch reels.json"
          if [ ! -s reels.json ]; then echo "reels.json is empty"; exit 1; fi
          cat reels.json # Content dikhao

      - name: Fetch profiles.json
        run: |
          curl -v -o ./profiles.json http://msmpr.free.nf/profiles.json || echo "Failed to fetch profiles.json"
          if [ ! -s profiles.json ]; then echo "profiles.json is empty"; exit 1; fi
          cat profiles.json # Content dikhao

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add reels.json profiles.json
          git status # Debugging
          git commit -m "Auto-update JSON files - $(date +%s)" || echo "No changes detected"
          git push || echo "Push failed, check logs"
