name: Update JSON files every minute

on:
  schedule:
    - cron: "*/1 * * * *"  # हर 1 मिनट में रन होगा
  workflow_dispatch:

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: रिपॉज़िटरी को क्लोन करें
        uses: actions/checkout@v3

      - name: JSON डेटा डाउनलोड करें (Python)
        run: |
          python -c "
          import requests;
          import json;
          headers = {'User-Agent': 'Mozilla/5.0'};
          url1 = 'http://msmpr.free.nf/profiles.json';
          url2 = 'http://msmpr.free.nf/reels.json';
          try:
              response1 = requests.get(url1, headers=headers, timeout=10)
              data1 = response1.json() if response1.status_code == 200 else {}
          except:
              data1 = {}
          try:
              response2 = requests.get(url2, headers=headers, timeout=10)
              data2 = response2.json() if response2.status_code == 200 else {}
          except:
              data2 = {}
          with open('profiles.json', 'w') as f1:
              json.dump(data1, f1)
          with open('reels.json', 'w') as f2:
              json.dump(data2, f2)
          "

      - name: गिट कमिट और पुश करें
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user
