name: Update JSON Files

on:
  schedule:
    - cron: "*/1 * * * *"  # हर 1 मिनट में ऑटोमैटिक अपडेट
  workflow_dispatch:  # मैन्युअली रन करने के लिए

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: GitHub Repository Clone करो
        uses: actions/checkout@v3

      - name: Python Install करो
        run: |
          sudo apt update
          sudo apt install python3 python3-pip -y

      - name: JSON डेटा डाउनलोड करो
        run: |
          python3 fetch_json.py

      - name: JSON फाइलें दिखाओ (Debugging)
        run: |
          ls -l profiles.json reels.json
          cat profiles.json
          cat reels.json

      - name: गिट कमिट और पुश करो (Force Update)
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add profiles.json reels.json
          git commit -m "Updated JSON data" || echo "No changes to commit"
          git push --force
